apiVersion: v1
kind: ConfigMap
metadata:
  name: populate-config
data:
  DB_HOST: eadskill-db.cbuauqyiweuf.us-west-2.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgresql
  DB_PASSWORD: postgresql
  DB_USER: postgresql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate
  namespace: eadskill
spec:
  template:
    metadata:
      labels:
        app: populate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: populate
          image: 399679827371.dkr.ecr.us-west-2.amazonaws.com/eadskill-populate:26
          command: ["/app/populate"]
          envFrom:
            - configMapRef:
                name: populate-config
